import { RequiredDataFromCollectionSlug } from 'payload'

type SuccessStorySeed = RequiredDataFromCollectionSlug<'success-stories'>

const createStory = (
  name: string,
  slug: string,
  category: 'judiciary' | 'adpo' | 'mains' | 'test-series' | 'interview',
  rank: number,
  year: number,
  exam: string,
  state: any, // Cast to any to avoid strict union typing in seed helper
  description: string,
  quote: string,
  highlight: string = "Aashayein's guidance was the key.",
  attempts: number = 1,
): SuccessStorySeed => ({
  name,
  slug,
  category,
  rank,
  rankDisplay: `AIR ${rank}`,
  year,
  exam,
  state: state,
  image: 1 as any, // Placeholder image ID, assuming 1 exists or will be remapped
  studentInfo: {
    currentPosition: category === 'adpo' ? 'ADPO' : 'Civil Judge (Junior Division)',
    location: `${state}`,
    education: 'LLB',
  },
  detailedDescription: description,
  testimonial: {
    quote,
    highlight,
  },
  journey: {
    totalAttempts: attempts,
    preparationDuration: '12-18 months',
    enrolledCourses: [], // Correct field name
    customCourses: [
      { courseName: category === 'adpo' ? 'ADPO Special Course' : 'Foundation Course' },
    ],
  },
  videoUrl: 'https://www.youtube.com/@aashayeinjudiciary',
  story: {
    introduction: `${name}'s journey is a shining example of persistence. Coming from a humble background, the dream of serving in the ${category === 'adpo' ? 'prosecution' : 'judiciary'} was fueled by a desire for justice.`,
    challenges: [
      { challenge: 'Managing time between college and preparation' },
      { challenge: 'Overcoming the fear of answer writing' },
      { challenge: 'Staying consistent during the long exam cycle' },
    ],
    turningPoint:
      'Joining Aashayein changed my perspective. The personalized mentorship helped me identify my weak areas.',
    preparation: {
      prelims: 'Focused on bare acts and repeated revision of MCQs.',
      mains: 'Daily answer writing and getting feedback was crucial.',
      interview: 'Mock interviews helped remove my hesitation and improved my body language.',
    },
  },
  timeline: [
    { period: 'Jan 2023', event: 'Started Preparation', icon: 'BookOpen' },
    { period: 'Dec 2023', event: 'Cleared Prelims', icon: 'CheckCircle' },
    { period: 'March 2024', event: 'Mains Success', icon: 'Award' },
    { period: 'May 2024', event: `Final Selection - AIR ${rank}`, icon: 'Trophy' },
  ],
  tips: [
    {
      title: 'Consistency is Key',
      description: 'Study everyday, even if it is for few hours.',
      icon: 'Calendar',
    },
    {
      title: 'Focus on Bare Acts',
      description: 'For prelims, your bare acts are your bible.',
      icon: 'BookOpen',
    },
  ],
  stats: [
    { label: 'Overall Rank', value: `AIR ${rank}` },
    { label: 'Exam Year', value: `${year}` },
  ],
  resources: [
    { resource: 'Comprehensive Notes' },
    { resource: 'Test Series' },
    { resource: 'Mock Interviews' },
  ],
})

export const successStorySeederData: SuccessStorySeed[] = [
  // --- JUDICIARY (6 items) ---
  createStory(
    'Priya Sharma',
    'priya-sharma',
    'judiciary',
    3,
    2024,
    'Delhi Judicial Service',
    'Delhi',
    'Priya secured AIR 3 with her dedicated answer writing practice.',
    "Aashayein's daily doubt sessions were invaluable.",
    'Personalized guidance made all the difference.',
    2,
  ),

  createStory(
    'Rajat Kumar',
    'rajat-kumar',
    'judiciary',
    8,
    2024,
    'UP Judicial Service',
    'Uttar Pradesh',
    'Rajat cleared UP Judiciary in his very first attempt.',
    'The test series helped me understand the exam pattern perfectly.',
    'Mock interviews were game-changers.',
  ),

  createStory(
    'Ananya Gupta',
    'ananya-gupta',
    'judiciary',
    12,
    2023,
    'MP Judicial Service',
    'Madhya Pradesh',
    'Ananya consistently topped our mock tests and translated that to the final exam.',
    'The structured approach of the foundation course kept me on track.',
    'Consistency beats intensity.',
    3,
  ),

  createStory(
    'Vikram Singh',
    'vikram-singh',
    'judiciary',
    15,
    2024,
    'Rajasthan Judicial Service',
    'Rajasthan',
    'From a vernacular background, Vikram mastered legal English with our support.',
    'Language was a barrier until I joined Aashayein. They helped me build confidence.',
    'Hard work pays off.',
    2,
  ),

  createStory(
    'Sneha Patil',
    'sneha-patil',
    'judiciary',
    22,
    2023,
    'Maharashtra Judicial Service',
    'Maharashtra',
    'Sneha managed her job and preparation to secure a top rank.',
    'The recorded lectures allowed me to study at my own pace after work.',
    'Flexible learning helped me succeed.',
  ),

  createStory(
    'Arjun Mehta',
    'arjun-mehta',
    'judiciary',
    5,
    2024,
    'Haryana Judicial Service',
    'Haryana',
    'Arjun focused heavily on case laws and recent judgments.',
    'The current legal knowledge provided by the faculty was exceptional.',
    'Focus on continuous improvement.',
  ),

  // --- ADPO (6 items) ---
  createStory(
    'Deepak Malhotra',
    'deepak-malhotra',
    'adpo',
    5,
    2024,
    'ADPO Rajasthan',
    'Rajasthan',
    "Deepak's strategic approach score him 89% in prelims.",
    'The ADPO-specific modules were excellent.',
    "Nitesh Sir's strategy was key.",
  ),

  createStory(
    'Sunita Verma',
    'sunita-verma',
    'adpo',
    2,
    2023,
    'ADPO MP',
    'Madhya Pradesh',
    'Sunita wanted to strengthen the prosecution side and worked hard on procedural laws.',
    'Detailed analysis of CrPC and IPC helped me score high.',
    'Clarity of concepts is essential.',
  ),

  createStory(
    'Mohit Saxena',
    'mohit-saxena',
    'adpo',
    10,
    2024,
    'ADPO UP',
    'Uttar Pradesh',
    'Mohit cleared the exam alongside his practice as an advocate.',
    'Practical insights from the faculty helped bridge the gap between theory and practice.',
    'Experience counts.',
    2,
  ),

  createStory(
    'Kavita Yadav',
    'kavita-yadav',
    'adpo',
    7,
    2023,
    'ADPO Bihar',
    'Bihar',
    'Kavita focused on local laws which are crucial for the state exam.',
    'The state-specific local laws classes were very detailed and helpful.',
    "Don't ignore local laws.",
  ),

  createStory(
    'Rahul Joshi',
    'rahul-joshi',
    'adpo',
    1,
    2024,
    'ADPO Chhattisgarh',
    'Chhattisgarh',
    'Rahul secured AIR 1 with a balanced strategy for law and GK.',
    'Aashayein covers General Knowledge as thoroughly as Law.',
    'Balanced preparation is the secret.',
  ),

  createStory(
    'Pooja Singh',
    'pooja-singh',
    'adpo',
    14,
    2024,
    'ADPO Haryana',
    'Haryana',
    'Pooja improved her speed significantly through our test series.',
    'Time management in the exam was my biggest takeaway from the mocks.',
    'Speed and accuracy matter.',
  ),

  // --- MAINS (6 items) ---
  createStory(
    'Siddharth Rao',
    'siddharth-rao',
    'mains',
    4,
    2024,
    'DJS Mains',
    'Delhi',
    'Siddharth had brilliant legal knowledge but struggled with structuring answers.',
    'The answer writing evaluation improved my presentation skills drastically.',
    'Presentation is as important as content.',
    2,
  ),

  createStory(
    'Meera Nair',
    'meera-nair',
    'mains',
    11,
    2023,
    'RJS Mains',
    'Rajasthan',
    'Meera focused on judgment writing which helped her edge past others.',
    'The judgment writing sessions simplified the complex format for me.',
    'Judgment writing is a skill.',
  ),

  createStory(
    'Varun Desai',
    'varun-desai',
    'mains',
    9,
    2024,
    'MPCJ Mains',
    'Madhya Pradesh',
    'Varun improved his mains score by 50 marks compared to his last attempt.',
    'Identifying key keywords for every answer helped me fetch extra marks.',
    'Keywords act as magnets for marks.',
    3,
  ),

  createStory(
    'Ishita Kapoor',
    'ishita-kapoor',
    'mains',
    6,
    2023,
    'UPPCS-J Mains',
    'Uttar Pradesh',
    'Ishita managed the vast syllabus of UP Mains with our concise notes.',
    'The consolidated notes for Mains saved me hours of revision time.',
    'Smart work over hard work.',
  ),

  createStory(
    'Rohan Das',
    'rohan-das',
    'mains',
    18,
    2024,
    'BJS Mains',
    'Bihar',
    'Rohan mastered the art of writing answers within the time limit.',
    'Timed tests simulated the real exam pressure perfectly.',
    'Practice under pressure.',
  ),

  createStory(
    'Kriti Sanon',
    'kriti-sanon',
    'mains',
    2,
    2024,
    'HJS Mains',
    'Haryana',
    'Kriti topped the mains written exam with her analytical answers.',
    'I learned how to interlink different sections and acts effectively.',
    'Interlinking is the key to good marks.',
  ),

  // --- TEST SERIES (6 items) ---
  createStory(
    'Amit Trivedi',
    'amit-trivedi',
    'test-series',
    25,
    2024,
    'All India Judicial Test Series',
    'All States',
    'Amit used our test series to gauge his standing at a national level.',
    'The leaderboard rankings motivated me to push harder every week.',
    'Competition drives excellence.',
  ),

  createStory(
    'Neha Gupta',
    'neha-gupta',
    'test-series',
    10,
    2023,
    'Prelims Test Series',
    'Delhi',
    'Neha practiced over 5000 questions through our platform.',
    'The explanation for every MCQ option cleared my concepts on the go.',
    'Learn from your mistakes.',
  ),

  createStory(
    'Rajesh Kumar',
    'rajesh-kumar',
    'test-series',
    30,
    2024,
    'Mains Test Series',
    'Uttar Pradesh',
    'Rajesh gives credit to the detailed feedback on his answer sheets.',
    'The remarks on my copies were so detailed, it felt like personal coaching.',
    'Feedback is the breakfast of champions.',
  ),

  createStory(
    'Simran Kaur',
    'simran-kaur',
    'test-series',
    15,
    2023,
    'State Specific Test Series',
    'Punjab',
    'Simran focused on the Punjab specific patterns provided in the tests.',
    'The mock tests mirrored the actual exam pattern of Punjab Judiciary.',
    'Exam specific preparation is must.',
  ),

  createStory(
    'Aditya Roy',
    'aditya-roy',
    'test-series',
    5,
    2024,
    'Comprehensive Test Series',
    'All States',
    'Aditya consistently scored high and built his confidence for the final day.',
    'Regular testing removed my exam anxiety completely.',
    'Confidence comes from preparation.',
  ),

  createStory(
    'Tanya Oza',
    'tanya-oza',
    'test-series',
    20,
    2024,
    'Rapid Revision Test Series',
    'Gujarat',
    'Tanya used the rapid revision tests for the last month preparation.',
    'The quick fire tests helped me revise the entire syllabus in 20 days.',
    'Revision is key.',
  ),

  // --- INTERVIEW (6 items) ---
  createStory(
    'Manish Pandey',
    'manish-pandey',
    'interview',
    7,
    2024,
    'Civil Judge Interview',
    'Bihar',
    'Manish was hesitant in speaking but transformed his personality.',
    'The panel members guided me on voice modulation and eye contact.',
    'Personality can be developed.',
  ),

  createStory(
    'Shreya Ghoshal',
    'shreya-ghoshal',
    'interview',
    3,
    2023,
    'RJS Interview',
    'Rajasthan',
    'Shreya scored one of the highest marks in the interview round.',
    'The situational questions asked in mocks prepared me for the tough board.',
    'Be ready for anything.',
  ),

  createStory(
    'Vivek Oberoi',
    'vivek-oberoi',
    'interview',
    12,
    2024,
    'MPCJ Interview',
    'Madhya Pradesh',
    'Vivek learned how to handle questions he did not know the answer to.',
    'I learned the art of saying "I dont know" politely and confidently.',
    'Honesty is appreciated.',
  ),

  createStory(
    'Priyanka Chopra',
    'priyanka-chopra',
    'interview',
    8,
    2023,
    'DJS Interview',
    'Delhi',
    'Priyanka polished her legal current affairs knowledge for the interview.',
    'The current affairs sessions for interview were spot on.',
    'Stay updated.',
  ),

  createStory(
    'Ranbir Singh',
    'ranbir-singh',
    'interview',
    19,
    2024,
    'UPPCS-J Interview',
    'Uttar Pradesh',
    'Ranbir focused on local dialect and state knowledge.',
    'The tips on cultural questions helped me connect with the board members.',
    'Know your state.',
  ),

  createStory(
    'Alia Bhatt',
    'alia-bhatt',
    'interview',
    4,
    2024,
    'HJS Interview',
    'Haryana',
    'Alia worked on her body language and sitting posture.',
    'Small things like how to enter the room make a big impression.',
    'First impression is the last impression.',
  ),
]
